# https://estafette.io/usage/manifest/#labels
labels:
  app: estafette-extension-npm-audit
  app-group: estafette-ci-extensions
  team: estafette-team
  language: golang

# https://estafette.io/usage/manifest/#versioning
version:
  semver:
    major: 0
    minor: 0

# https://estafette.io/usage/manifest/#build-stages
stages:
  build:
    image: golang:1.15.6-alpine3.12
    env:
      CGO_ENABLED: 0
      GOOS: linux
    commands:
    - go test ./...
    - go build -a -installsuffix cgo -ldflags "-X main.appgroup=${ESTAFETTE_LABEL_APP_GROUP} -X main.app=${ESTAFETTE_GIT_NAME} -X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=${ESTAFETTE_GIT_REVISION} -X main.branch=${ESTAFETTE_GIT_BRANCH} -X main.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./publish/${ESTAFETTE_GIT_NAME} .

  # https://estafette.io/usage/extensions/estafette-extensions/#extensions-docker
  bake:
    image: extensions/docker:dev
    action: build
    repositories:
    - extensions
    container: npm-audit
    path: ./publish
    copy:
    - /etc/ssl/certs/ca-certificates.crt

  check-container:
    parallelStages:
      check-efficiency:
        image: extensions/docker:dev
        action: dive
        container: npm-audit
        repositories:
        - extensions

      vulnerability-scan:
        image: extensions/docker:dev
        action: trivy
        container: npm-audit
        repositories:
        - extensions

  push-to-docker-registry:
    image: extensions/docker:dev
    action: push
    repositories:
    - extensions
    container: npm-audit

  # https://estafette.io/usage/extensions/estafette-extensions/#extensions-slack-build-status
  slack-notify:
    image: extensions/slack-build-status:dev
    workspace: travix
    channels:
    - '#builds-${ESTAFETTE_LABEL_TEAM}'
    when:
      status == 'failed'

# https://estafette.io/usage/manifest/#releases
releases:
  dev:
    triggers:
    - pipeline:
        name: self
        branch: .+
    stages:
      tag-container-image:
        image: extensions/docker:dev
        action: tag
        container: npm-audit
        repositories:
        - extensions
        tags:
        - dev

  beta:
    stages:
      tag-container-image:
        image: extensions/docker:dev
        action: tag
        container: npm-audit
        repositories:
        - extensions
        tags:
        - beta

      slack-notify:
        image: extensions/slack-build-status:dev
        workspace: estafette
        channels:
        - '#build-status'
        when:
          status == 'succeeded' ||
          status == 'failed'

  stable:
    stages:
      tag-container-image:
        image: extensions/docker:dev
        action: tag
        container: npm-audit
        repositories:
        - extensions
        tags:
        - stable
        - latest

      slack-notify:
        image: extensions/slack-build-status:dev
        workspace: estafette
        channels:
        - '#build-status'
        when:
          status == 'succeeded' ||
          status == 'failed'
